# Generated by Django 4.2.11 on 2024-04-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_service'),
        ('bookings', '0002_alter_booking_additional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='rooms.service', verbose_name='Дополнительные услуги'),
        ),
    ]
