# Generated by Django 4.2.11 on 2024-04-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bill',
            field=models.PositiveIntegerField(default=1000, verbose_name='Стоимость бронирования'),
            preserve_default=False,
        ),
    ]
