# Generated by Django 4.2.11 on 2024-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Число гостей, которые будут проживать в номере'),
            preserve_default=False,
        ),
    ]
