# Generated by Django 4.2.11 on 2024-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_services', '0001_initial'),
        ('bookings', '0006_booking_guests_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='additional_services.service', verbose_name='Дополнительные услуги'),
        ),
    ]
