# Generated by Django 4.2.11 on 2024-04-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
