# Generated by Django 5.0.4 on 2024-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'удобства',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер комнаты')),
                ('layout_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('family', 'Семейный'), ('luxury', 'Люкс'), ('studio', 'Студия'), ('apartment', 'Апартаменты'), ('business', 'Бизнес-номер')], max_length=20, verbose_name='Тип планировки')),
                ('cost_per_day', models.PositiveIntegerField(verbose_name='Стоимость проживания (р/день)')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('maintenance', 'Ремонт')], max_length=20, verbose_name='Состояние номера')),
                ('facilities', models.ManyToManyField(to='rooms.amenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'комнаты',
            },
        ),
    ]
