# Generated by Django 5.0.4 on 2024-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_facilities_room_amenities_alter_amenity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты'),
        ),
    ]
