# Generated by Django 4.2.11 on 2024-04-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание планировки')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'комнаты',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='layout_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты/апартаментов'),
        ),
        migrations.AddField(
            model_name='room',
            name='layout_type',
            field=models.ManyToManyField(to='rooms.layout', verbose_name='Тип планировки'),
        ),
    ]
