# Generated by Django 4.2.11 on 2024-04-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_layoutimage_options_layout_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='min_price',
        ),
    ]
