# Generated by Django 4.2.11 on 2024-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_layout_capacity_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
    ]
