# Generated by Django 4.2.11 on 2024-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='layout',
            name='amenities',
            field=models.ManyToManyField(to='rooms.amenity', verbose_name='Удобства'),
        ),
    ]
