# Generated by Django 4.2.11 on 2024-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_layout_accessible_for_disabled_layout_number_of_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='possible_with_children',
            field=models.BooleanField(default=1, verbose_name='Можно с детьми'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='possible_with_pets',
            field=models.BooleanField(default=1, verbose_name='Можно с животными'),
            preserve_default=False,
        ),
    ]
