# Generated by Django 4.2.11 on 2024-04-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cost_per_day',
        ),
        migrations.AddField(
            model_name='layoutimage',
            name='cost_per_day',
            field=models.PositiveIntegerField(default=1000, verbose_name='Стоимость проживания (р/день)'),
            preserve_default=False,
        ),
    ]
