# Generated by Django 4.2.11 on 2024-04-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_remove_room_cost_per_day_layoutimage_cost_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutimage',
            name='cost_per_day',
        ),
        migrations.AddField(
            model_name='layout',
            name='cost_per_day',
            field=models.PositiveIntegerField(default=1200, verbose_name='Стоимость проживания (р/день)'),
            preserve_default=False,
        ),
    ]
