# Generated by Django 4.2.11 on 2024-04-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_remove_layoutimage_cost_per_day_layout_cost_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='layout_type',
        ),
        migrations.AddField(
            model_name='room',
            name='layout_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.layout', verbose_name='Тип планировки'),
            preserve_default=False,
        ),
    ]
