# Generated by Django 4.2.11 on 2024-04-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_remove_room_layout_type_room_layout_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
