# Generated by Django 4.2.11 on 2024-04-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_additional_services'),
        ('rooms', '0018_remove_room_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
