# Generated by Django 4.2.11 on 2024-04-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='media/user_photos/'),
        ),
    ]
