# Generated by Django 4.2.11 on 2024-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='user_photos/'),
        ),
    ]
